#!/bin/sh

#copy the entire library into /urs/local/include
#so you the user can just #include <generator_utils>

find *.hpp -exec cp {} /usr/local/include \;
cp generator_utils /usr/local/include/generator_utils
cp graph_utils /usr/local/include/graph_utils